### ISSUE TITLE
HTTP -> AMQP

### ISSUE THREAD

**Issue by rurounijones** [rack-amqp/jackalope#2]
Based on what I have seen so far I assume there is a component whose responsibility is to put the HTTP requests onto rabbitMQ in the first place so it can then be picked up by apps running on jackalope.

I am thinking that a simple evented app running on event-machine with the amqp_gem whose job is basically to do nothing but hand-off to rabbitMQ.
1. Is my thinking correct?
2. Does such a simple sample app exist? (I have looked around various repos but nothing obvious comes to mind.)

**Comment by jszmajda** [comment]
Hey, sorry for the delay. You're right, there's a system that sends messages to jackalope over amqp, it's the https://github.com/rack-amqp/rack-amqp-client gem, or (simpler to use and acts like HTTParty) https://github.com/rack-amqp/amqparty. These are both gems you would use in-process inside whichever requesting app you're writing, so your app will end up connecting to Rabbit itself.

As for an example, I have a little bit written over at https://github.com/rack-amqp/rails-demo. The `interface` app is a vanilla rails app that uses the `userland_client` gem to connect to Rabbit and communicate via AMQP with `userland`, which is intended to be a rails app running on jackalope.

It's all a bit rough right now, so if there's anything else I can help clear up please don't hesitate to ask! I'll try to be a bit more prompt next time answering :)

**Comment by rurounijones** [comment]
Thanks for the information. Ok, so basically the demo is http -> rails_app_1 -> amqp -> rails_app_2

There is currently no http -> _minimal_forwarder_app_ -> amqp -> rails_app

Where minimal_forwarder_app literally has app specific logic. Its only job is to take an incoming http request and forward it to amqp (almost like a simple http proxy except we convert to amqp).

If I understand things correctly I think we could have a canonical minimal "This app does nothing but forward an incoming request to rabbitmq broker specified somewhere (ENV, config file etc)" logic-less async I/O app running on thin for example. Is there anything you can think of that would prevent this?
